name: HunterHelper
main: com.loganhi.hunterhelper.HunterHelper
version: 0.01
commands:
   basic:
      description: This is a demo command.
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>